- type: log
  processors:
  - decode_csv_fields:
      fields:
        message: decoded
      separator: ","
      ignore_missing: false
      overwrite_keys: true
      trim_leading_space: false
      fail_on_error: true

  - extract_array:
      field: decoded
      mappings:
        name: 0
        age: 1
        
  - drop_fields:
      fields: ["decoded"]
      ignore_missing: true
  paths:
    - /home/filebeat/data/test.csv
  scan_frequency: 5s