- type: log
  processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: false
      add_error_key: true

 
  paths:
    - /home/filebeat/data/test.json
  scan_frequency: 5s